#!/usr/bin/env /ptv/healer/healerdb-py/.venv/bin/python3
# -*- coding: utf-8 -*-
import os, sys, inspect
import mod_dbquery as dbquery
from rich import print
from rich.console import Console
from rich.markdown import Markdown
from rich.theme import Theme
from rich.emoji import Emoji
import mod_utils as myutils
from mod_utils import *

# Clear the terminal screen
clear()

# Set up rich
console = Console()

# Logo string
logo = """# HealerDB
## A CLI Tool to manage the database of Healer
### For Help, just run the command with the -h flag: `healerdb -h`
##### Made with :brain:  and :muscle:  by [Autherix](https://github.com/autherix)
###### By :handshake:  with: [Barbod](https://github.com/dark190)
"""

# print the logo
mdview(logo)

seperator()

# define connection string
connHostPort = "localhost:27017"
connUsername = "healerdb"
connSecret = "hamidpapi"
connstr = "mongodb://"+connUsername+":"+connSecret+"@"+connHostPort+"/"
print("Connecting to mongodb server on: \n" + str(connHostPort))
seperator()

# Create a client to the mongodb database using the connstr
client, err = dbquery.CreateClient(connstr)
if err != None:
    print("[red][ERR][/red] Main: CreateClient: \n", err)
    sys.exit(1)

# Purge all the databases except admin and config
err = dbquery.PurgeDatabases(client)
if err != None:
    print("[red][ERR][/red] Main: PurgeDatabases: \n", err)
    # sys.exit(1)

# Create a database called 'enum'
dbname = "enum"
err = dbquery.CreateDatabase(client, dbname)
if err != None:
    print("[red][ERR][/red] Main: CreateDatabase: \n", err)
    # sys.exit(1)

# Create a target called 'target1'
collname = "target1"
err = dbquery.AddTarget(client, dbname, collname)
if err != None:
    print("[red][ERR][/red] Main: AddTarget: \n", err)
    # sys.exit(1)

# Create a target called 'target2'
collname = "target2"
err = dbquery.AddTarget(client, dbname, collname)
if err != None:
    print("[red][ERR][/red] Main: AddTarget: \n", err)
    # sys.exit(1)

# List all databases names and print them
dbs, err = dbquery.GetDatabases(client)
if err != None:
    print("[red][ERR][/red] Main: GetDatabases: \n", err)
    # sys.exit(1)

# List all collection names in database 'enum' and print them
colls, err = dbquery.GetCollections(client, dbname)
if err != None:
    print("[red][ERR][/red] Main: GetCollections: \n", err)
    # sys.exit(1)
print("Main: GetCollections: colls: \n"+ str(colls))

# Add a domain to database 'enum' and collection 'target1', domain = 'target1.com', use insertDomain function
domain = "target1.com"
collname = "target1"
domain, err = dbquery.InsertDomain(client, dbname, collname, domain)
if err != None:
    print("[red][ERR][/red] Main: InsertDomain: \n", err)
    # sys.exit(1)
print("Main: InsertDomain: domain: \n"+ str(domain))
    
# Add subdomain to it using AddSubdomain function
domain = "target1.com"
collname = "target1"
subdomain = "sub1"
domain, err = dbquery.AddSubdomain(client, dbname, collname, domain, subdomain)
if err != None:
    print("[red][ERR][/red] Main: AddSubdomain: \n", err)
    # sys.exit(1)
